spring:
  datasource:
    url: jdbc:h2:mem:wallettest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas para os testes de integração
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false

logging:
  level:
    root: WARN
    org.springframework.test.context: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE